FROM python:3.11-slim

WORKDIR /app

RUN pip install streamlit pandas plotly

COPY app.py .
COPY weather_raw.csv .
COPY hotels_raw.csv .
COPY cities.csv .

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]